services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:inc
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    image: nginx:inc
    container_name: nginx
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inc
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  redis:
    build: ./requirements/bonus/redis
    image: redis:inc
    container_name: redis
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:inc
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - 8080:8080

  website:
    build: ./requirements/bonus/website
    image: website:inc
    container_name: website
    restart: always
    networks:
      - inception
    ports:
      - 8085:8085

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer:inc
    container_name: portainer
    restart: always
    networks:
      - inception
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  ftp :
    build : ./requirements/bonus/ftp/
    image: ftp:inc
    container_name : ftp
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks : 
      - inception
    env_file:
      - .env
    ports:
      - "21:21"
      - "10000-10010:10000-10010"
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/schahir/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/schahir/data/wordpress

networks:
  inception: